### ISSUE TITLE
Support for additional Dapr APIs

### ISSUE THREAD

**Issue by mukundansundar** [Roadwork/dapr-js-sdk#1]
I was wondering if support for the following Dapr APIs be added to this SDK:

bulk API for state bulkGet https://docs.dapr.io/reference/api/state_api/#get-bulk-state
Transaction API support https://docs.dapr.io/reference/api/state_api/#state-transactions
Secrets API support https://docs.dapr.io/reference/api/secrets_api/

Actors API (Client side calling actors) : https://docs.dapr.io/reference/api/actors_api/

**Comment by XavierGeerinck** [comment]
Will add those asap

**Comment by XavierGeerinck** [comment]
Hi @mukundansundar, those have now been added and additional tests were added as well. Let me know if I forgot some

**Comment by XavierGeerinck** [comment]
Hi @mukundansundar any update on this?

**Comment by mukundansundar** [comment]
Sorry for the late reply. The changes look good to me.
